#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;
use Mojolicious::Lite;

use Yote::SpiderPup;

my $dir = $ARGV[0] || $ENV{SPIDERPUP} || '../www';
my $app = app;
Yote::SpiderPup->launch( $dir, $app );
